# Generated by Django 2.0.3 on 2018-03-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180319_1010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieActors',
            new_name='PersonMovie',
        ),
    ]
